version: '3.8'

services:
  app:
    image: outfortheseason/whiskeyhabits
    container_name: whiskeyhabits
    build: .
    ports:
      - "6161:3001"
    environment:
      - DB_URL=mongodb://mongo:27017/whiskeyhabits
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
